import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from '@/lib/router.jsx';
import { motion } from 'framer-motion';
import { ArrowRight, Sparkles } from 'lucide-react';
import { BorderMotif } from '@/components/brand';
export function HeroBanner() {
    return (_jsxs("section", { className: "relative min-h-[90vh] flex items-center overflow-hidden bg-[#1a0e0e]", children: [_jsx("div", { className: "absolute inset-0 opacity-10", style: {
                    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100'%3E%3Cpath d='M50 10 C35 10 22 22 22 38 C22 54 35 61 47 58 C41 64 41 75 50 77 C59 75 59 64 53 58 C65 61 78 54 78 38 C78 22 65 10 50 10Z' fill='%23C9933A' opacity='1'/%3E%3Ccircle cx='50' cy='38' r='6' fill='%23C9933A'/%3E%3C/svg%3E")`,
                    backgroundSize: '100px 100px',
                } }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-[#1a0e0e] via-[#1a0e0e]/90 to-[#1a0e0e]/60" }), _jsx("div", { className: "absolute top-0 left-0 right-0", children: _jsx("div", { className: "h-1 bg-gradient-to-r from-transparent via-[#C9933A] to-transparent" }) }), _jsxs("div", { className: "relative z-10 max-w-7xl mx-auto px-4 sm:px-6 py-20 grid lg:grid-cols-2 gap-12 items-center", children: [_jsxs("div", { children: [_jsxs(motion.p, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.1 }, className: "text-xs tracking-[0.4em] text-[#C9933A] uppercase mb-4 flex items-center gap-2", children: [_jsx("span", { className: "w-6 h-px bg-[#C9933A]" }), "India's Grandest Jewellery Store", _jsx("span", { className: "w-6 h-px bg-[#C9933A]" })] }), _jsx(motion.h1, { initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.2 }, className: "heading-display text-white mb-2", style: { fontFamily: 'var(--font-cormorant)' }, children: "Jewellery That" }), _jsx(motion.h1, { initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.3 }, className: "heading-display gold-text mb-6", style: { fontFamily: 'var(--font-cormorant)' }, children: "Tells Your Story" }), _jsx(motion.p, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.4 }, className: "text-[#9e9790] text-lg leading-relaxed max-w-lg mb-8", children: "Exquisite BIS hallmarked jewellery crafted with centuries-old Indian artisanal traditions. From bridal sets to everyday elegance \u2014 all in 8K detail." }), _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.5 }, className: "flex flex-wrap gap-4", children: [_jsxs(Link, { href: "/shop", className: "btn-gold text-sm px-8 py-3.5 flex items-center gap-2", children: ["Explore Collection", _jsx(ArrowRight, { size: 16 })] }), _jsxs(Link, { href: "/tryon", className: "btn-outline-gold text-sm px-8 py-3.5 flex items-center gap-2 border-[#C9933A]/60 text-[#E8C97A] hover:border-[#C9933A] hover:text-[#E8C97A]", children: [_jsx(Sparkles, { size: 16 }), "Try-On in 3D"] })] }), _jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.7 }, className: "flex flex-wrap gap-4 mt-8", children: [
                                    { value: '50K+', label: 'Happy Customers' },
                                    { value: '10K+', label: 'Designs' },
                                    { value: '100%', label: 'BIS Hallmarked' },
                                    { value: '4.9★', label: 'Avg Rating' },
                                ].map((badge) => (_jsxs("div", { className: "text-center", children: [_jsx("p", { className: "text-xl font-bold gold-text-static", style: { fontFamily: 'var(--font-cormorant)' }, children: badge.value }), _jsx("p", { className: "text-[10px] text-[#6B6560] uppercase tracking-wider", children: badge.label })] }, badge.label))) })] }), _jsx(motion.div, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 0.4, duration: 0.8 }, className: "hidden lg:flex items-center justify-center", children: _jsxs("div", { className: "relative w-96 h-96", children: [_jsx("div", { className: "absolute inset-0 flex items-center justify-center opacity-20", children: _jsx("img", { src: "/motifs/mandala.svg", alt: "", className: "w-full h-full animate-[mandala-spin_20s_linear_infinite]" }) }), _jsx("div", { className: "absolute inset-8 rounded-full border-2 border-[#C9933A]/30 flex items-center justify-center bg-[#2a1212]/50 backdrop-blur-sm", children: _jsxs("div", { className: "text-center p-8", children: [_jsx("div", { className: "text-5xl mb-2", children: "\uD83D\uDC8E" }), _jsx("p", { className: "text-[#E8C97A] text-sm font-medium", style: { fontFamily: 'var(--font-cormorant)' }, children: "New Bridal Collection 2025" }), _jsx("p", { className: "text-[#C9933A] text-xs mt-1 tracking-wider uppercase", children: "Coming This Season" })] }) }), [
                                    { label: '22K Gold', pos: 'top-2 left-4', delay: 0.6 },
                                    { label: 'Diamond', pos: 'top-2 right-4', delay: 0.8 },
                                    { label: 'Kundan', pos: 'bottom-2 left-4', delay: 1.0 },
                                    { label: 'Polki', pos: 'bottom-2 right-4', delay: 1.2 },
                                ].map((tag) => (_jsx(motion.div, { initial: { opacity: 0, scale: 0 }, animate: { opacity: 1, scale: 1 }, transition: { delay: tag.delay }, className: `absolute ${tag.pos} px-3 py-1.5 bg-[#C9933A]/20 border border-[#C9933A]/40 rounded-full text-xs text-[#E8C97A] font-medium backdrop-blur-sm`, children: tag.label }, tag.label)))] }) })] }), _jsx("div", { className: "absolute bottom-0 left-0 right-0", children: _jsx(BorderMotif, {}) })] }));
}
